import React from 'react';
import { Eye, ShieldAlert, Cpu, Sparkles, HelpCircle } from 'lucide-react';

interface DataTransparencyGuideProps {
  className?: string;
}

export function DataTransparencyGuide({ className = '' }: DataTransparencyGuideProps) {
  const tiers = [
    {
      title: 'OBSERVED',
      icon: Eye,
      badgeClass: 'bg-[#EDF7F1] text-[#154D2F] border-[#ABD7C0]',
      description:
        'Direct physical ground truth and instrument measurements. Includes IMD automatic weather stations (AWS), Visakhapatnam Doppler radar, INSAT-3DR radiometers, and Survey of India boundary vectors. Represents verifiable physical reality.',
      example: 'AWS rainfall at Semiliguda, radar reflectivity dBZ, INSAT-3DR PWV.',
    },
    {
      title: 'OFFICIAL FORECAST',
      icon: ShieldAlert,
      badgeClass: 'bg-[#EAF0F6] text-[#0B1F33] border-[#CBD5E1]',
      description:
        'Statutory operational advisories and forecast bulletins officially published by the India Meteorological Department (IMD) and OUAT Gramin Krishi Mausam Sewa (GKMS). Official government-authorized weather guidance.',
      example: 'IMD 5-day Koraput district weather forecast bulletin.',
    },
    {
      title: 'MODEL PREDICTION',
      icon: Cpu,
      badgeClass: 'bg-[#EAF5FC] text-[#0E63A8] border-[#B9DCF4]',
      description:
        'Algorithmic numerical weather prediction (NWP) simulations and calibrated machine-learning outputs (NCMRWF NCUM, ECMWF ERA5, Bayesian probability distributions). Subject to uncertainty bounds and lead-time decay.',
      example: 'Downscaled 14-day rainfall outlook, 850 hPa LLJ zonal reversal trajectory.',
    },
    {
      title: 'SIMULATION',
      icon: Sparkles,
      badgeClass: 'bg-[#FCEDEC] text-[#802626] border-[#EEA9A7]',
      description:
        'Synthetic prototype runs and demonstrative benchmark scenarios generated by the SIH 2026 evaluation engine. Strictly tagged with "DEMO MODEL OUTPUT" to eliminate the hazard of misinterpreting simulated data as live observations.',
      example: 'Dry spell probability threshold stress tests on /overview and /officer.',
    },
  ];

  return (
    <div className={`bg-white rounded-md border border-[#E2E8F0] shadow-gov-card p-4 space-y-3.5 ${className}`}>
      <div className="flex items-center justify-between border-b border-[#E2E8F0] pb-2.5">
        <div className="flex items-center gap-2">
          <div className="p-1 rounded-xs bg-[#EAF0F6] text-[#1479C9]">
            <HelpCircle className="w-4 h-4 text-[#1479C9]" />
          </div>
          <div>
            <h3 className="text-sm font-bold uppercase tracking-wider text-[#0B1F33] font-mono">
              EPISTEMIC TRANSPARENCY & DATA PROVENANCE FRAMEWORK
            </h3>
            <span className="text-[11px] text-[#6E7F94] font-mono">
              Institutional commitment ensuring every data point communicates its empirical certainty
            </span>
          </div>
        </div>

        <span className="text-[10px] font-mono font-bold px-2 py-0.5 rounded-xs bg-[#0B1F33] text-white">
          4 DATA TIERS
        </span>
      </div>

      {/* 4 Cards Grid */}
      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-3">
        {tiers.map((tier) => {
          const Icon = tier.icon;
          return (
            <div
              key={tier.title}
              className="p-3.5 rounded-md border border-[#CBD5E1] bg-[#FAFCFE] space-y-2 flex flex-col justify-between"
            >
              <div>
                <div className="flex items-center justify-between">
                  <span
                    className={`font-mono text-xs font-bold px-2 py-0.5 rounded-xs border uppercase inline-flex items-center gap-1.5 ${tier.badgeClass}`}
                  >
                    <Icon className="w-3 h-3" />
                    <span>{tier.title}</span>
                  </span>
                </div>

                <p className="text-[11px] text-[#334155] leading-relaxed mt-2">
                  {tier.description}
                </p>
              </div>

              <div className="pt-2 border-t border-[#E2E8F0] text-[10px] font-mono text-[#6E7F94]">
                <strong className="text-[#0B1F33]">Example:</strong> {tier.example}
              </div>
            </div>
          );
        })}
      </div>
    </div>
  );
}
