import React from 'react';
import { Eye, ShieldAlert, Cpu, Sparkles, HelpCircle } from 'lucide-react';

interface DataTransparencyGuideProps {
  className?: string;
}

export function DataTransparencyGuide({ className = '' }: DataTransparencyGuideProps) {
  const tiers = [
    {
      title: 'OBSERVED',
      icon: Eye,
      badgeClass: 'bg-emerald-950/40 text-emerald-300 border-emerald-500/40',
      description:
        'Direct physical ground truth and instrument measurements. Includes IMD automatic weather stations (AWS), Visakhapatnam Doppler radar, INSAT-3DR radiometers, and Survey of India boundary vectors. Represents verifiable physical reality.',
      example: 'AWS rainfall at Semiliguda, radar reflectivity dBZ, INSAT-3DR PWV.',
    },
    {
      title: 'OFFICIAL FORECAST',
      icon: ShieldAlert,
      badgeClass: 'bg-cyan-950/40 text-cyan-300 border-cyan-500/40',
      description:
        'Statutory operational advisories and forecast bulletins officially published by the India Meteorological Department (IMD) and OUAT Gramin Krishi Mausam Sewa (GKMS). Official government-authorized weather guidance.',
      example: 'IMD 5-day Koraput district weather forecast bulletin.',
    },
    {
      title: 'MODEL PREDICTION',
      icon: Cpu,
      badgeClass: 'bg-blue-950/40 text-blue-300 border-blue-500/40',
      description:
        'Algorithmic numerical weather prediction (NWP) simulations and calibrated machine-learning outputs (NCMRWF NCUM, ECMWF ERA5, Bayesian probability distributions). Subject to uncertainty bounds and lead-time decay.',
      example: 'Downscaled 14-day rainfall outlook, 850 hPa LLJ zonal reversal trajectory.',
    },
    {
      title: 'SIMULATION',
      icon: Sparkles,
      badgeClass: 'bg-amber-950/40 text-amber-300 border-amber-500/40',
      description:
        'Synthetic prototype runs and demonstrative benchmark scenarios generated by the SIH 2026 evaluation engine. Strictly tagged with "DEMO MODEL OUTPUT" to eliminate the hazard of misinterpreting simulated data as live observations.',
      example: 'Dry spell probability threshold stress tests on /overview and /officer.',
    },
  ];

  return (
    <div className={`bg-[#0A192F]/85 rounded-xl border border-[#1E354D] shadow-2xl p-5 space-y-4 backdrop-blur-md ${className}`}>
      <div className="flex items-center justify-between border-b border-[#1E354D] pb-3">
        <div className="flex items-center gap-2.5">
          <div className="p-1.5 rounded-lg bg-cyan-950/60 text-cyan-400 border border-cyan-500/30">
            <HelpCircle className="w-4 h-4 text-cyan-400" />
          </div>
          <div>
            <h3 className="text-sm font-black uppercase tracking-wider text-white font-mono">
              EPISTEMIC TRANSPARENCY & DATA PROVENANCE FRAMEWORK
            </h3>
            <span className="text-[11px] text-slate-400 font-mono">
              Institutional commitment ensuring every data point communicates its empirical certainty
            </span>
          </div>
        </div>

        <span className="text-[10px] font-mono font-bold px-2.5 py-1 rounded-lg bg-cyan-950/50 text-cyan-300 border border-cyan-500/40">
          4 DATA TIERS
        </span>
      </div>

      {/* 4 Cards Grid */}
      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-3.5">
        {tiers.map((tier) => {
          const Icon = tier.icon;
          return (
            <div
              key={tier.title}
              className="p-4 rounded-xl border border-[#1E354D] bg-[#071324] space-y-2.5 flex flex-col justify-between hover:border-cyan-500/40 transition-colors"
            >
              <div>
                <div className="flex items-center justify-between">
                  <span
                    className={`font-mono text-xs font-bold px-2.5 py-1 rounded-lg border uppercase inline-flex items-center gap-1.5 ${tier.badgeClass}`}
                  >
                    <Icon className="w-3.5 h-3.5" />
                    <span>{tier.title}</span>
                  </span>
                </div>

                <p className="text-[11px] text-slate-300 leading-relaxed mt-2.5">
                  {tier.description}
                </p>
              </div>

              <div className="pt-2.5 border-t border-[#1E354D] text-[10px] font-mono text-slate-400">
                <strong className="text-cyan-400">Example:</strong> {tier.example}
              </div>
            </div>
          );
        })}
      </div>
    </div>
  );
}
